### ISSUE TITLE
Wikia sites support 

### ISSUE THREAD

**Issue by PhongTong** [WPCleaner/wpcleaner#7]
Can you make a support for wikis from wikia hosting site? Thanks

**Comment by WPCleaner** [comment]
Thanks for the suggestion. I will look into it when I have some free time, but it will need quite some work as wikia (a site for creating many many small wikis) is very different from wikipedia (a stable list of wikis).
I believe I need to add a feature so that users can add their own wiki in the list.

**Comment by Kumioko** [comment]
If it helps, AutoWikiBrowser has functionality like this. You might be able to view how it does it and implement some variant of that. I would love to be able to use this on Wikia as well.

**Comment by WPCleaner** [comment]
Moved to Phabricator. https://phabricator.wikimedia.org/T256234
